---
# tasks file for consul
- name: ensure directory exists
  file: path=/data/consul/ state=directory
- debug: msg="command line:{{consul_argline}}"
- name: consul container
  docker:
    image: "progrium/consul"
    state: started
    name: "{{ansible_hostname}}_consul"
    restart_policy: always
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
#      - "{{ansible_docker0.ipv4.address}}:53:53/udp"
    volumes:
      - "/data/consul:/data" 
    command: "{{consul_argline}}"
- name: install dnsmasq
  apt: name=dnsmasq
- name: use consul for dns resolution
  lineinfile: create=yes state=present dest=/etc/dnsmasq.d/10-consul line="server=/consul/{{ansible_docker0.ipv4.address}}#53"
