---
# Creating a single consul container (only for development purposes)
- hosts: controller
  tasks:
    - name: consul container
      docker:
        image: "progrium/consul"
        state: started
        ports:
          - "8400:8400"
          - "8500:8500"
          - "8600:53/udp"
        hostname: consul1
        command: -server -bootstrap -ui-dir /ui
