---
# Creating a single consul container (only for development purposes)
- hosts: controller
  roles:
     - { role: "consul", consul_argline: "-server -node {{ansible_hostname}} -bootstrap-expect 3 -advertise 192.168.205.11 -ui-dir /ui" }

- hosts: 
    - graylog
    - repository
  roles:
     - { role: "consul", consul_argline: "-server -node {{ansible_hostname}} -advertise {{ansible_eth1.ipv4.address}}  -join 192.168.205.11" }
- hosts:
    - dockerhosts
    - cdslaves
  roles:
     - { role: "consul", consul_argline: "-node {{ansible_hostname}} -advertise {{ansible_eth1.ipv4.address}} -join 192.168.205.11 -join 192.168.205.17 -join 192.168.205.14" }
