---
- hosts: 
    - graylog
    - dockerhosts
    - cdslaves
    - controller
    - repository
  tasks:
    - name: update kernel and aufs
      apt: name={{ item }} state=present
      with_items:
        - linux-generic-lts-vivid
        - linux-image-extra-{{ansible_kernel}}
        - aufs-tools
  roles:
    - { role: angstwad.docker_ubuntu, docker_opts: "{{ docker_options }}" }
