# registers a registrator on each docker node
# should only be started after consul is available
---
- hosts: all
  tasks:
    - name: registrator
      docker:
        image: "gliderlabs/registrator:latest"
        hostname: registrator
        command: "consul://localhost:8500 -h {{ansible_hostname}} -resync 10 -ttl 120 -ttl-refresh 60"
        name: "registrator"
        state: started
        restart_policy: always
        restart_policy_retry: 2
        volumes: 
          - /var/run/docker.sock:/tmp/docker.sock
        

