# registers a registrator on each docker node
# should only be started after consul is available
---
- hosts: all
  tasks:
    - name: registrator
      docker:
        image: "gliderlabs/registrator:latest"
        hostname: registrator
        command: "consul://{{ansible_eth1.ipv4.address}}:8500 -ip {{ansible_eth1.ipv4.address}} -h {{ansible_hostname}} -resync 10"
#        command: "consul://192.168.205.11:8500 -ip {{ansible_eth1.ipv4.address}} -h {{ansible_hostname}} -resync 10"
#        command: "consul://192.168.205.11:8500"
        name: "registrator"
        state: restarted
        restart_policy: always
        restart_policy_retry: 2
        volumes: 
          - /var/run/docker.sock:/tmp/docker.sock
        

