---
- hosts: 
    - swarm
    - controller
    - repository
    - graylog
  tasks:
    - name: create swarm member
      docker:
        image: "swarm"
        name: "swarm-member"
        state: started
        restart_policy: always
        command: "join --advertise={{ansible_eth1.ipv4.address}}:2375 consul://192.168.205.11:8500" 
    
- hosts: controller
  tasks:
    - name: create swarm manager
      docker:
        image: "swarm"
        name: "swarm-manager"
        state: started
        restart_policy: always
        command: "manage consul://192.168.205.11:8500"
        ports:
          - "12375:2375"

# On any of the swarm nodes create the network
# currently is not the best solution (creates a file only on the node where network was created)
# better execute script before creating network that checks for network (docker network ls) and
# creates or deletes file
- hosts: controller
  tasks:
    - name: check for multihost network
      shell: docker network ls | awk '{print $2}' | grep multihost
      register: multihost_network_available
    - name: Create overlay network
      command: docker network create --driver overlay multihost
      when: multihost_network_available.stdout != 'multihost'
