# vim: noai:ts=2:sw=2:expandtab
---
- debug: msg="User is set to {{user}} home is {{home}}" 

- name: install vim packages
  apt: name={{item}} state=present 
  with_items:
    - vim-gtk
    - build-essential
    - cmake
    - python-dev
  tags: vim

- name: Ensure .vim directory exists
  file: path={{home}}/.fonts state=directory

- name: Install Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest={{home}}/.vim/bundle/Vundle.vim
  environment: proxy_env
  tags: vim
  become: true
  become_user: "{{user}}"

- name: Download vimrc
  get_url: url="https://gist.githubusercontent.com/rattermeyer/4f2b0d48069a2f5345fd/raw/0df71628a7134950543042ef68ff5234911f1601/vimrc" dest={{home}}/.vimrc
  environment: proxy_env
  tags: vim
  notify: Plugins Install
  become: true
  become_user: "{{user}}"

# Install Powerline Font support
# not sure if this is enough
- name: Install Powerline Font
  file: path={{home}}/.fonts state=directory
  tags: vim
  become: true
  become_user: "{{user}}"
- get_url: url="https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf" dest={{home}}/.fonts
  environment: proxy_env
  tags: powerline
  notify: fc-cache update
  become: true
  become_user: "{{user}}"

- file: path={{home}}/.config/fontconfig/conf.d state=directory 
  tags: [powerline, vim]
  become: true
  become_user: "{{user}}"

- get_url: url="https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf" dest={{home}}/.config/fontconfig/conf.d/10-powerline-symbols.conf
  environment: proxy_env
  tags: [powerline, vim]
  become: true
  become_user: "{{user}}"

## end: Powerline

- name: YouCompleteMe
  git: repo=https://github.com/Valloric/YouCompleteMe.git dest={{home}}/.vim/bundle/YouCompleteMe
  become: true
  become_user: "{{user}}"

- name: YouCompleteMe compile
  command: ./install.py --clang-completer creates="{{home}}/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_client_support.so" chdir="{{home}}/.vim/bundle/YouCompleteMe"
  become: true
  become_user: "{{user}}"

